name: Pull Request or Push

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  azure_login_and_ci:
    name: Azure Login and CI
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run CI Workflow
        uses: salt-extensions/central-artifacts/.github/workflows/ci.yml@main
        with:
          setup-vault: true
